services:
  db:
    container_name: db
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: computer_use
    ports:
      - "5432:5432"
  
  app:
    container_name: app
    build: .
    ports:
      - "8000:8000"
      - "5900:5900"
      - "6080:6080"
    env_file:
      - .env
    depends_on:
      - db